### ISSUE TITLE
How save file on my server

### ISSUE THREAD

**Issue by optigopl** [Flagbit/Magento-MEP#20]
Hi,
I have problem with "save file".
Path to export is correct. Directory have privileges 777. 
My path to export is still empty :( 
I generate manuall (click RUN). I try also manual run cron: mywebste/mep-cron.php
Nothing... 

I check preview export -> preview work good.

Please help me!

<img width="447" alt="magento_administrator" src="https://user-images.githubusercontent.com/32541199/32392521-4bbcfa90-c0d6-11e7-9dfd-8baf532c3f1c.png">

**Comment by bjoern-flagbit** [comment]
Hey, can you try to run shell/mep.php with the profile number you need? 
And maybe see if there is an error. Greetings.

**Comment by optigopl** [comment]
Yes, sure.
Please write, "what command to use" - What should a command look like?
Greetings.

**Comment by bjoern-flagbit** [comment]
Yes ;-) i will close this issue.
