### ISSUE TITLE
Run button not work

### ISSUE THREAD

**Issue by DevCPL** [flagbit/Magento-MEP#21]
Hi, 
I have a problem with the RUN button for magento MEP. When i click that button he says that process is been scheduled in 59 seconds, but in the export folder there is nothing. Can anyone help me?

![screen1](https://user-images.githubusercontent.com/52622244/60766243-61a9a080-a0a7-11e9-8401-9afa0c447f64.png)

![screen2](https://user-images.githubusercontent.com/52622244/60766244-62423700-a0a7-11e9-8fd8-52e97660c30c.png)

**Comment by bjoern-flagbit** [comment]
The button just "scheduled" the job (put an entry in the db) ... but you also need to setup the mep-cron.php as Cronjob. This file is looking for the scheduled jobs and then execute them.

https://github.com/flagbit/Magento-MEP/blob/master/src/mep-cron.php
