### ISSUE TITLE
Root Category Filter Does Not Work

### ISSUE THREAD

**Issue by sprankhub** [Flagbit/Magento-MEP#5]
Hi,

if I use a category filter and just select a root category, I would expect that all products are exported, which are activated in one of the subcategories of this root category. But currently, random products or products from other categories are exported in this case. If I select all subcategories by hand and select "is one of" in the filter, it works perfectly. But what happens if a new category is added? Then I will have to think of my export profile and change it by hand. This is not feasible.

Hence, I would kindly ask you to implement this feature: If one selects a root category in the filter, all products should be exported which are activated in one of the subcategories of this root category.

Thank you in advance
Simon

**Comment by sprankhub** [comment]
Thanks for the commit @proxium! Unfortunately, it still does not work for me. If I only select a root category, I get 1456 products. If I select each of the subcategories, I get 749 products.

**Comment by bjoern-flagbit** [comment]
We tried again to reproduce with a magento default store and demo data. But there is no issue. So we decided to NOT merge the MAGEMEP-171 because it is duplicate code. Issue closed.
